#=========== Site settings ===========
title: "INSTITUCION EDUCATICA DISTRITAL JUAN JOSE NEIRA MACHETA CUNDINAMARCA"
email: pmolano22@gmail.com # Used for Github project forumspree.io HTML Forums Made Easy and FREE
description: > # this means to ignore newlines until "url:"
  Repositorio digital para la didáctica de las ciencias naturales a través de  la aplicación powtoon, con los estudiantes de la  IED Juan José Neira, municipio de Machetá, Cundinamarca
url: "iedjuanjoseneiramachetacund.github.io" # the base hostname & protocol for your site
paginate: 4 # NEEDS to stay at 4 to work
#=========== Gems ===========
gems: [IEDJUANJOSENEIRAMACHETACUND-paginate]
#=========== 1st Page Video ===========
video_tittle: "Factores bióticos y abióticos"
video_alt: Factores bióticos y abióticos
video_url: https://www.youtube.com/watch?v=AFgZZSnEyAM # just URL
video_upload_date:
video_description: > # this means to ignore newlines until "Facebook_ID:"
  Write an awesome description for your video site here. You can edit
  this line in _config.yml. It will appear in the capption under the video
#=========== Facebook/Google ID ===========
Facebook_ID: false # Turns on Facebook Open Graph meta data  / ON: {Your Facebook Page ID} OFF: False
Google_ID: false # Google Analytics ID
#===========  Disqus Username ===========
disqus_user:  # Need for Comments / Turn on comments: in Post
#============= Social Media ===============
social:
  - title: twitter
    url: https://twitter.com/jekyllrb # @USERNAME without @ / Only Need for Twitter Feed
  - title: github
    url: https://github.com/IEDJUANJOSENEIRAMACHETACUND
#=========== Build settings ===========
markdown: kramdown
permalink: /:BIBLIOTECA VIRTUAL
#=========== Default Settings ===========
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: post
